services:
  - type: web
    name: telecharger-mp3-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get update && apt-get install -y ffmpeg
    startCommand: python app.py
    plan: free
